package main

type HeartbeatStatus uint

const (
	HEARTBEAT_EXITED HeartbeatStatus = iota
	HEARTBEAT_NOTFOUND
	HEARTBEAT_FOUND
)

const (
	INCOMING_ID         = 0
	INCOMING_TYPE       = 1
	INCOMING_LENGTH     = 2
	INCOMING_DATA_START = 3
	INCOMING_DATA_END   = 29
	INCOMING_STATE      = 30

	OUTGOING_ID         = 31
	OUTGOING_TYPE       = 32
	OUTGOING_LENGTH     = 33
	OUTGOING_DATA_START = 34
	OUTGOING_DATA_END   = 60
	OUTGOING_STATE      = 61

	INIT_STATE = 63
)

const (
	STATE_INCOMING_IDLE      = 0
	STATE_INCOMING_BUSY      = 1
	STATE_INCOMING_AVAILABLE = 2

	STATE_OUTGOING_IDLE      = 0
	STATE_OUTGOING_AVAILABLE = 1
)

const (
	INIT_EXPECTED_VALUE   = 56
)
